Detailed page
greenfox-zerda-raptors/ZerdaReaderAndroid pull request #13
Opened 2017-01-31 09:55 UTC by regnisalram

2017-02-01 13:01 UTC, regnisalram commented
changed it up so detailedpage is now an activity, clicking on item starts it with the right object. pls pull?

2017-02-01 14:00 UTC, adamgyulavari requested changes

2017-02-01 14:00 UTC, adamgyulavari commented on app/src/main/AndroidManifest.xml
>  </manifest>
@regnisalram  new line

2017-02-01 14:00 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/DetailedPageActivity.java
> +        NewsItem newsItem = (NewsItem) i.getSerializableExtra("newsItem");
@regnisalram dont need intent for anything else, just chain it getIntent().getS...

2017-02-01 14:08 UTC, regnisalram commented on app/src/main/AndroidManifest.xml
>  </manifest>
done

2017-02-01 14:08 UTC, regnisalram commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/DetailedPageActivity.java
> +        NewsItem newsItem = (NewsItem) i.getSerializableExtra("newsItem");
done

2017-02-02 11:03 UTC, adamgyulavari requested changes

2017-02-02 11:03 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/LoginActivity.java
> +        MockServer apiService = new MockServer();
@regnisalram use injected apiService isntead

2017-02-02 12:00 UTC, adamgyulavari approved these changes

2017-02-02 12:00 UTC, adamgyulavari commented
@regnisalram resolve conflicts

2017-02-02 12:20 UTC, regnisalram commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/LoginActivity.java
> +        MockServer apiService = new MockServer();
done

2017-02-02 13:16 UTC, regnisalram commented
everything should be ok now

2017-02-02 15:13 UTC, merged