handle favorites
greenfox-zerda-raptors/ZerdaReaderAndroid pull request #15
Opened 2017-02-01 10:55 UTC by Anna812

- create endpoint handling in retrofit for favorites
- make feedfragment use parameter to handle feed and favorite feed
- update pageradapter

2017-02-01 14:06 UTC, adamgyulavari commented
@Anna812 resolve conflicts

2017-02-01 14:58 UTC, Anna812 commented
conflicts resolved :)

2017-02-02 11:05 UTC, adamgyulavari requested changes

2017-02-02 11:05 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/FeedFragment.java
> +        args.putInt("someInt", someInt);
@Anna812 can we name this meaningful instead "someInt". eg: a boolean named onlyFavorites

2017-02-02 11:37 UTC, Anna812 commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/FeedFragment.java
> +        args.putInt("someInt", someInt);
changed to tabNumber as it should indicate which tab are you on, maybe we will add a third one just for fun :)

2017-02-02 12:01 UTC, adamgyulavari approved these changes

2017-02-02 12:01 UTC, merged