Zsuzsi userresponse error
greenfox-zerda-raptors/ZerdaReaderAndroid pull request #16
Opened 2017-02-01 13:38 UTC by vikukzs

2017-02-01 14:10 UTC, adamgyulavari requested changes

2017-02-01 14:10 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/LoginActivity.java
> +    String email, password;
@vikukzs you dont need to store these as class variables

2017-02-01 14:10 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/LoginActivity.java
> +        Call<UserResponse> call = apiService.loginUser(email, password);
@vikukzs just pass to the parameters the getText...

2017-02-01 14:25 UTC, vikukzs commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/LoginActivity.java
> +    String email, password;
done, i think

2017-02-01 14:26 UTC, vikukzs commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/LoginActivity.java
> +        Call<UserResponse> call = apiService.loginUser(email, password);
done, i think

2017-02-02 11:06 UTC, adamgyulavari requested changes

2017-02-02 11:06 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/LoginActivity.java
> +                checkCredentialsAndLogIn();
@vikukzs checking if the editTexts are empty should be before sending an "empty" request to the server

2017-02-02 11:06 UTC, adamgyulavari commented
@vikukzs also resolve conflicts!

2017-02-02 11:14 UTC, vikukzs commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/LoginActivity.java
> +                checkCredentialsAndLogIn();
i thought it does that...?

2017-02-02 11:26 UTC, vikukzs commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/LoginActivity.java
> +                checkCredentialsAndLogIn();
oh i think i got it.

2017-02-02 12:02 UTC, adamgyulavari approved these changes

2017-02-02 12:02 UTC, merged