Subscriptions settings fragment
greenfox-zerda-raptors/ZerdaReaderAndroid pull request #17
Opened 2017-02-01 13:51 UTC by zsofinnemeth

activities instead of fragments.
I added buttons that navigate back to the main activity because the default android back button (of the phone) exits the app

2017-02-01 14:18 UTC, adamgyulavari requested changes

2017-02-01 14:18 UTC, adamgyulavari commented on app/src/main/AndroidManifest.xml
>  </manifest>
@zsofinnemeth empty line

2017-02-01 14:18 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/MainActivity.java
> +                break;
@zsofinnemeth dont finish the activity

2017-02-01 14:18 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/MainActivity.java
> +                startActivity(j);
dont finish it here as well

2017-02-01 14:18 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/MainActivity.java
> +                startActivity(i);
@zsofinnemeth you dont need the intent anymore, just instantuate it in the parameters

2017-02-01 14:18 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/ManageSubscriptionsActivity.java
> +        Button backButton = (Button) findViewById(R.id.subscriptionBack);
@zsofinnemeth button should be in the toolbar as a back icon

2017-02-01 14:44 UTC, zsofinnemeth commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/ManageSubscriptionsActivity.java
> +        Button backButton = (Button) findViewById(R.id.subscriptionBack);
added a backlog for myself to trello

2017-02-01 14:44 UTC, zsofinnemeth commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/MainActivity.java
> +                startActivity(j);
OK

2017-02-01 14:44 UTC, zsofinnemeth commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/MainActivity.java
> +                break;
OK

2017-02-01 14:44 UTC, zsofinnemeth commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/MainActivity.java
> +                startActivity(i);
OK

2017-02-01 14:46 UTC, zsofinnemeth commented on app/src/main/AndroidManifest.xml
>  </manifest>
OK

2017-02-01 15:59 UTC, zsofinnemeth commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/ManageSubscriptionsActivity.java
> +        Button backButton = (Button) findViewById(R.id.subscriptionBack);
@adamgyulavari it is done too!

2017-02-02 11:08 UTC, adamgyulavari approved these changes

2017-02-02 11:08 UTC, merged