Zsuzsi login activity test
greenfox-zerda-raptors/ZerdaReaderAndroid pull request #31
Opened 2017-02-14 10:29 UTC by vikukzs

2017-02-15 12:27 UTC, adamgyulavari requested changes

2017-02-15 12:27 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/model/NewsItem.java
> +        return false;
@vikukzs why?

2017-02-15 12:27 UTC, adamgyulavari commented on app/src/main/res/values/strings.xml
> +    <!--<string name="email">username</string>-->
@vikukzs remove instead of comment

2017-02-15 12:36 UTC, vikukzs commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/model/NewsItem.java
> +        return false;
can't remember. should be favorite, shouldn't it?

2017-02-17 09:21 UTC, adamgyulavari approved these changes

2017-02-17 09:21 UTC, merged