Detailedpage design
greenfox-zerda-raptors/ZerdaReaderAndroid pull request #33
Opened 2017-02-15 11:01 UTC by regnisalram

title says it all

2017-02-15 12:30 UTC, adamgyulavari requested changes

2017-02-15 12:30 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/server/MockServer.java
> +                        "Cupcake croissant icing sugar plum jelly. Oat cake donut jelly apple pie chocolate cake. Muffin bonbon chocolate bar tootsie roll. Soufflé lemon drops danish pie pudding dess
@regnisalram you can use this, instead of this burned in data: https://github.com/blocoio/faker

2017-02-15 13:53 UTC, regnisalram commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/server/MockServer.java
> +                        "Cupcake croissant icing sugar plum jelly. Oat cake donut jelly apple pie chocolate cake. Muffin bonbon chocolate bar tootsie roll. Soufflé lemon drops danish pie pudding dess
everything's SUPER slow this way, android studio keeps logging stuff like this:
![screen shot 2017-02-15 at 14 52 12](https://cloud.githubusercontent.com/assets/12460484/22977316/6fff5896-f38e-11e6-8e01-4e12682d69c3.png)

2017-02-17 09:24 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/server/MockServer.java
> +//                d1, "Fox Crunch", false, true));
@regnisalram remove these comments if this is working after all

2017-02-17 09:47 UTC, regnisalram commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/server/MockServer.java
> +//                d1, "Fox Crunch", false, true));
i don't think that the first solution should be left in, it's way too slow, the second didn't work at the end, so can i just put back the hardcoded fake data or should i look for a third kind of datafaker?

2017-02-22 10:09 UTC, adamgyulavari approved these changes

2017-02-22 10:09 UTC, merged