Base activity, timestamp saving to sharedpreferences
greenfox-zerda-raptors/ZerdaReaderAndroid pull request #34
Opened 2017-02-15 13:23 UTC by zsofinnemeth

2017-02-17 09:29 UTC, adamgyulavari requested changes

2017-02-17 09:29 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/BaseActivity.java
> +        Long timestamp = System.currentTimeMillis()/1000;
@zsofinnemeth dont need to divide by 1000

2017-02-17 09:29 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/BaseActivity.java
> +    SharedPreferences timePreferences;
@zsofinnemeth this is a default sharedpreferences, not just the time can be stored in here, so name it like that

2017-02-17 09:29 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/BaseActivity.java
> +        editor.putLong("timestamp", timestamp);
@zsofinnemeth all these lines could be in one line (timestamp variable never used again, editor never used again)

2017-02-17 09:45 UTC, zsofinnemeth commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/BaseActivity.java
> +        editor.putLong("timestamp", timestamp);
the editor is used, so I could chop down only one line

2017-02-17 09:45 UTC, zsofinnemeth commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/BaseActivity.java
> +        Long timestamp = System.currentTimeMillis()/1000;
done, sorry

2017-02-17 09:46 UTC, zsofinnemeth commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/BaseActivity.java
> +    SharedPreferences timePreferences;
done this on a different branch and forgot about it eventually.. corrected it.

2017-02-20 14:47 UTC, adamgyulavari approved these changes

2017-02-20 14:47 UTC, merged