background sync
greenfox-zerda-raptors/ZerdaReaderAndroid pull request #37
Opened 2017-02-20 13:17 UTC by Anna812

Setup alarm manager
Is enabled/disabled from Settings
BroadcastReceiver updates feed, and sends Event on Eventbus
Feedfragment is Subscribed to this event, and updates listview

2017-02-20 14:57 UTC, adamgyulavari requested changes

2017-02-20 14:57 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/FeedFragment.java
>                  adapter.addAll(response.body());
@Anna812 why not just the 98th line? why the need to store them in a variable?

2017-02-20 14:57 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/SettingsActivity.java
> +                PendingIntent.FLAG_UPDATE_CURRENT);
@Anna812 refactor this to a method and use it in the schedule as well

2017-02-20 14:57 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/backgroundSync/BackgroundSyncReceiver.java
> +                news = response.body();
@Anna812 Eventbus posting should be here.

2017-02-20 15:22 UTC, Anna812 commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/FeedFragment.java
>                  adapter.addAll(response.body());
no idea, but deleted unnecessary lines

2017-02-20 15:22 UTC, Anna812 commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/activity/SettingsActivity.java
> +                PendingIntent.FLAG_UPDATE_CURRENT);
done

2017-02-20 15:22 UTC, Anna812 commented on app/src/main/java/com/greenfox/fuchsit/zerdareader/backgroundSync/BackgroundSyncReceiver.java
> +                news = response.body();
done

2017-02-21 12:32 UTC, adamgyulavari approved these changes

2017-02-21 12:32 UTC, adamgyulavari commented
@Anna812 resolve conflicts

2017-02-21 13:48 UTC, Anna812 commented
resolved conflicts with master

2017-02-22 10:08 UTC, adamgyulavari approved these changes

2017-02-22 10:08 UTC, merged